name: build-kernel [MIUI]
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Prepare timezone 
      run: |
            echo "BUILD_TIME=$(TZ=Asia/Jakarta date "+%d%m%Y-%H%M")" >> $GITHUB_ENV
            sudo rm /etc/localtime
            sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
        
    - name: Install Dependencies
      run: |
           sudo apt update -y
           sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 -y
           sudo aptitude install libssl-dev -y
                
    - name: clone Zyc clang 21.0.0git
      run: |
            mkdir clang && cd clang && curl -LO https://raw.githubusercontent.com/ZyCromerZ/Clang/main/Clang-main-link.txt && zyc-clang.tar.gz && tar -xvf zyc-clang.tar.gz -C clang && rm -rf zyc-clang.tar.gz

    - name: clone GCC arm64 & arm32
      run: |
            git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 gcc64
            git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 gcc32
            
    - name: clone KernelSU-Next 
      run: |
           curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs-dev
                              
    - name: Build 
      run: |
           export ARCH=arm64
           export PATH="${PWD}/clang/bin:${PWD}gcc64/bin:${PWD}gcc32/bin:${PATH}"
           export KBUILD_BUILD_USER=nobody
           export KBUILD_BUILD_HOST=android-build 
           export KBUILD_COMPILER_STRING="${PWD}/clang"
           make O=out sweet_defconfig 
           make -j$(nproc --all) O=out \ ARCH=arm64 \ LLVM=1 \ LLVM_IAS=1 \ CC=clang \ CLANG_TRIPLE=aarch64-linux-gnu- \ CROSS_COMPILE=aarch64-linux-gnu- \ CROSS_COMPILE_ARM32=arm-linux-gnueabi-
           mv out/.config out/sweet_defconfig.txt
           
    - name: Upload defconfig 
      uses: actions/upload-artifact@v4
      with:
        name: defconfig-${{ env.BUILD_TIME }}
        path: out/sweet_defconfig.txt
      
    - name: Priper Image
      run: |
            git clone --depth=1 https://github.com/clrowex/Anykernel3 -b main AnyKernel3 
            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
            cp out/arch/arm64/boot/dtb.img AnyKernel3/dtb.img
               
    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: sweet-MIUI-${{ env.BUILD_TIME }}
        path: AnyKernel3/*



    
